language: python
os: linux

jobs:
  include:
    - name: "Linux, Python 3.8-dev, OpenMPI, newest packages"
      python: "3.8-dev"
      dist: focal
      before_install:
        - sudo `which pip` install --upgrade pip
        - pip install numpy
      before_script:
        - pip install -U $(cat requirements.txt | awk -F '==|>=' {'print $1'})
      env: MPI=openmpi
    - name: "Linux, Python 3.8, OpenMPI, required packages"
      python: 3.8
    - name: "Linux, Python 3.8, MPICH, required packages"
      python: 3.8
      env: MPI=mpich
    - name: "Linux, Python 3.8, no MPI, required packages"
      python: 3.8
      env: MPI=none
    - name: "OSX, Python 3.8, OpenMPI, required packages"
      language: shell
      os: osx
      before_install:
        - export PY_SFX=3
        - export HOMEBREW_NO_INSTALL_CLEANUP=1
        - export HOMEBREW_NO_AUTO_UPDATE=1
    - name: "Windows, Python 3.8, MS-MPI, required packages, tests"
      language: shell
      os: windows
      before_install:
        - choco install python --version 3.8.2
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - |
    if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      export apt_get_install="sudo apt-get install --no-install-recommends"
      if [[ $MPI == 'none'    ]]; then sed -i '/mpi4py/d' requirements.txt || exit 1; fi
      if [[ $MPI == 'mpich'   ]]; then $apt_get_install mpich libmpich-dev || exit 1; fi
      if [[ $MPI == 'openmpi' ]]; then $apt_get_install openmpi-bin libopenmpi-dev || exit 1; fi
      $apt_get_install ffmpeg || exit 1;
    fi;
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install open-mpi; fi
  - |
    if [[ $TRAVIS_OS_NAME == 'windows' ]]; then
      WEB_ADDRESS=https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1
      curl -L $WEB_ADDRESS/msmpisetup.exe -o msmpisetup.exe || exit 1;
      curl -L $WEB_ADDRESS/msmpisdk.msi -o msmpisdk.msi || exit 1;
      ./msmpisetup.exe || exit 1;
      msiexec //i msmpisdk.msi || exit 1;
      export PATH=/c/Program\ Files/Microsoft\ MPI/bin:$PATH
    fi;
  - pip$PY_SFX install -U pytest
  - pip$PY_SFX install -U -r requirements.txt

script:
  - python$PY_SFX -m numba -s
  - | 
    if [[ $MPI != 'none' ]]; then
      MPIEXEC="mpiexec -n 2 $([ "$MPI" == 'openmpi' ] && echo "--oversubscribe")"
    fi;
  - $MPIEXEC python$PY_SFX -m pytest numba_mpi_tests || exit 1;
  # execute Python lines from README.md
  - awk < README.md 'BEGIN {cmt=1; swp=0;} {swp=(substr($0,1,3)=="```"); if (swp && !cmt) {cmt=1; swp=0} if (cmt) print("#" $0); else print $0; if (swp && cmt) {cmt=0; swp=0}}' | python$PY_SFX
